micronaut:
  application:
    name: rest-service
  server:
    port: "${SERVICE_PORT:8082}"
    cors:
      enabled: true
      configurations:
        all:
          allowedOrigins:
            - "${FRONTEND_URL:}"
  security:
    authentication: idtoken
    oauth2:
      clients:
        google:
          client-id: '${OAUTH_CLIENT_ID:xxx}'
          client-secret: '${OAUTH_CLIENT_SECRET:yyy}'
          openid:
            issuer: 'https://accounts.google.com'
    endpoints:
      logout:
        get-allowed: true
    redirect:
      login-success: 'http://localhost:3000'
    token:
      jwt:
        cookie:
          cookie-http-only: false
      writer:
        header:
          enabled: true
      propagation:
        enabled: true
        service-id-regex: "view-service"
  #    enabled: true
  #    authentication: bearer
  #    token:
  #      jwt:
  #        signatures:
  #          secret:
  #            generator:
  #              secret: pleaseChangeThisSecretForANewOne
  #      writer:
  #        header:
  #          enabled: true
  #      propagation:
  #        enabled: true
  #        service-id-regex: "view-service"
  http:
    services:
      view-service:
        urls:
          - "http://localhost:8082"

datasources:
  default:
    driver-class-name: com.mysql.cj.jdbc.Driver
    db-type: mysql

r2dbc:
  datasources:
    default:
      dialect: MYSQL
      db-type: mysql

endpoints:
  health:
    enabled: true
    details-visible: ANONYMOUS

liquibase:
  datasources:
    default:
      change-log: 'classpath:db/changelog.xml'

jackson:
  serialization-inclusion: NON_NULL

netty:
  default:
    allocator:
      max-order: 3

#logger.levels:
#  io.micronaut.context: TRACE
