micronaut:
  server:
    port: "${SERVICE_PORT:8082}"
    cors:
      enabled: true
      configurations:
        all:
          allowedOrigins:
            - "${FRONTEND_URL:}"
  application:
    name: restService
  security:
    authentication: idtoken
    oauth2:
      clients:
        google:
          client-id: '${OAUTH_CLIENT_ID:xxx}'
          client-secret: '${OAUTH_CLIENT_SECRET:yyy}'
          openid:
            issuer: 'https://accounts.google.com'
    endpoints:
      logout:
        get-allowed: true
    redirect:
      login-success: 'http://localhost:3000'

datasources:
  default:
    username: "${DB_USERNAME:user}"
    password: "${DB_PASSWORD:pass}"
    #    schema-generate: CREATE_DROP
    url: jdbc:mysql://${DB_URL:localhost}/test?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    driverClassName: com.mysql.cj.jdbc.Driver
    connection-timeout: 600000
    validation-timeout: 600000
    max-lifetime: 600000
    idle-timeout: 120000
    maximum-pool-size: 50
    minimum-idle: 10

netty:
  default:
    allocator:
      max-order: 3
