micronaut:
  application:
    name: rest-service
  server:
    port: "${SERVICE_PORT:8082}"
    cors:
      enabled: true
      configurations:
        all:
          allowedOrigins:
            - "${FRONTEND_URL:}"
  security:
    authentication: idtoken
    oauth2:
      clients:
        google:
          client-id: '${OAUTH_CLIENT_ID:xxx}'
          client-secret: '${OAUTH_CLIENT_SECRET:yyy}'
          openid:
            issuer: 'https://accounts.google.com'
    endpoints:
      logout:
        get-allowed: true
    redirect:
      login-success: 'http://localhost:3000'
    token:
      jwt:
        cookie:
          cookie-http-only: false
#        signatures:
#          secret:
#            generator:
#              secret: pleaseChangeThisSecretForANewOne

datasources:
  default:
    driver-class-name: com.mysql.cj.jdbc.Driver
    db-type: mysql

r2dbc:
  datasources:
    default:
      dialect: MYSQL
      db-type: mysql

endpoints:
  health:
    enabled: true
    details-visible: ANONYMOUS

liquibase:
  datasources:
    default:
      change-log: 'classpath:db/changelog.xml'

jackson:
  serialization-inclusion: ALWAYS

netty:
  default:
    allocator:
      max-order: 3
